# Generated by Django 4.2.26 on 2025-11-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_status', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='red', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='usersignup',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('operator', 'Traffic Operator'), ('admin', 'Administrator')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='VehicleDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lane', models.CharField(default='main', max_length=50)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trafficsignal')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('alert_level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trafficsignal')),
            ],
        ),
    ]
