# Generated by Django 4.2.26 on 2025-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trafficsignal_remove_usersignup_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='role',
        ),
        migrations.AddField(
            model_name='usersignup',
            name='confirm_password',
            field=models.CharField(default='Alex@123', max_length=20),
            preserve_default=False,
        ),
    ]
